# Generated by Django 3.2.5 on 2021-07-23 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrs', '0005_remove_sources_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rrsfeeditems',
            name='feed',
        ),
        migrations.AddField(
            model_name='sources',
            name='description_chanal',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sources',
            name='description_post',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sources',
            name='image_chanal',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='sources',
            name='image_post',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='sources',
            name='lastBuildDate',
            field=models.DateTimeField(null=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='sources',
            name='link_post',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sources',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='sources',
            name='title_post',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='RrsFeed',
        ),
        migrations.DeleteModel(
            name='RrsFeedItems',
        ),
    ]
