# Generated by Django 3.2.5 on 2021-07-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrs', '0006_auto_20210723_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sources',
            name='pub_date',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
    ]
