# Generated by Django 3.2.5 on 2021-07-24 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrs', '0007_alter_sources_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sources',
            name='description_chanal',
        ),
        migrations.RemoveField(
            model_name='sources',
            name='description_post',
        ),
        migrations.RemoveField(
            model_name='sources',
            name='image_chanal',
        ),
        migrations.RemoveField(
            model_name='sources',
            name='image_post',
        ),
        migrations.RemoveField(
            model_name='sources',
            name='link_post',
        ),
        migrations.RemoveField(
            model_name='sources',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='sources',
            name='title_post',
        ),
        migrations.AlterField(
            model_name='sources',
            name='lastBuildDate',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='RrsFeedItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_post', models.CharField(db_index=True, max_length=200, null=True)),
                ('link_post', models.CharField(db_index=True, max_length=200, null=True)),
                ('image_post', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('description_post', models.TextField(null=True)),
                ('pub_date', models.CharField(max_length=200, null=True)),
                ('soures', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrs.sources')),
            ],
        ),
    ]
