# Generated by Django 3.2.5 on 2021-07-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrs', '0008_auto_20210724_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rrsfeeditems',
            name='image_post',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
