# Generated by Django 3.2.5 on 2021-07-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrs', '0010_auto_20210724_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='rrsfeeditems',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='rrsfeeditems',
            name='pub_date',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sources',
            name='lastBuildDate',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
