# Generated by Django 3.2.5 on 2021-07-24 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrs', '0012_rrsfeeditems_date2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rrsfeeditems',
            name='date',
        ),
    ]
