# Generated by Django 3.2.5 on 2021-07-24 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrs', '0013_remove_rrsfeeditems_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rrsfeeditems',
            name='date2',
        ),
        migrations.AddField(
            model_name='rrsfeeditems',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
