# Generated by Django 3.2.5 on 2021-07-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrs', '0014_auto_20210724_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rrsfeeditems',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
