# Generated by Django 3.2.5 on 2021-07-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrs', '0016_rrsfeeditems_data_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='Категория ленты', max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Категории',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.AddField(
            model_name='rrsfeeditems',
            name='categories',
            field=models.ManyToManyField(null=True, related_name='categories_post', to='rrs.CategoriesPost'),
        ),
    ]
